"""Initial database schema

Revision ID: c7fc87bf2713
Revises: 
Create Date: 2026-08-07 20:42:21.199594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7fc87bf2713'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_country', sa.String(length=100), nullable=False),
    sa.Column('preferred_degree', sa.String(length=100), nullable=False),
    sa.Column('target_field', sa.String(length=255), nullable=False),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('english_test', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholarships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('university', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('funding', sa.String(length=100), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('application_link', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documents_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_page_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_link')
    )
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('pages_scanned', sa.Integer(), nullable=False),
    sa.Column('scholarships_found', sa.Integer(), nullable=False),
    sa.Column('new_scholarships', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_logs')
    op.drop_table('scholarships')
    op.drop_table('user_profile')
    op.drop_table('sources')
    # ### end Alembic commands ###
